require('dotenv').config();
const mongoose = require('mongoose');
const Hospital = require('./models/Hospital');

const hospitals = [
  { hospitalName: "AIIMS Bhopal", fullName: "All India Institute of Medical Sciences Bhopal", type: "Government – Teaching & Research", category: "Super Speciality", area: "Saket Nagar", address: "AIIMS Campus Rd, AIIMS Campus, Saket Nagar, Habib Ganj, Bhopal, MP 462020", emergency: true, phone: "+91-755-298-2607", totalBeds: 960, availableBeds: 450, icuBeds: 100, icuAvailable: 25, ventilators: 80, ventilatorsAvailable: 15, specialties: ["General Medicine", "Surgery", "Cardiology", "Neurology", "Oncology", "Orthopedics", "Pediatrics", "Gynecology", "Radiology", "Psychiatry"], accreditation: ["NABH", "MCI"], ayushmanEmpanelled: true, coordinates: { lat: 23.2094, lng: 77.4582 }, googlePlaceId: "ChIJ19uXWs1DfDkRwEhb7dOe29s", rating: 4.0, ratingCount: 1895, open24x7: true, status: "green" },
  { hospitalName: "Hamidia Hospital", fullName: "Hamidia Hospital (Gandhi Medical College)", type: "Government – Teaching", category: "Tertiary Care", area: "Royal Market", address: "Sultania Rd, Royal Market, Bhopal, MP 462001", emergency: true, phone: "+91-755-254-0590", totalBeds: 1500, availableBeds: 600, icuBeds: 120, icuAvailable: 30, ventilators: 100, ventilatorsAvailable: 20, specialties: ["General Medicine", "Surgery", "Orthopedics", "Gynecology", "Pediatrics", "Cardiology", "Neurology", "Emergency Medicine", "ENT", "Ophthalmology"], accreditation: ["MCI"], ayushmanEmpanelled: true, coordinates: { lat: 23.2592, lng: 77.3942 }, googlePlaceId: "ChIJD0xmDxtofDkRjXtQa8xpj9w", rating: 3.2, ratingCount: 783, open24x7: true, status: "green" },
  { hospitalName: "Gandhi Medical College", fullName: "Gandhi Medical College & Hospital", type: "Government – Teaching", category: "Tertiary Care", area: "Royal Market", address: "Sultania Rd, Near Hamidia Hospital, Royal Market, Bhopal, MP 462001", emergency: true, phone: "+91-755-254-0590", totalBeds: 1000, availableBeds: 400, icuBeds: 80, icuAvailable: 15, ventilators: 60, ventilatorsAvailable: 10, specialties: ["General Medicine", "Surgery", "Pathology", "Radiology", "Dermatology", "Plastic Surgery", "Burns", "Oncology"], accreditation: ["MCI"], ayushmanEmpanelled: true, coordinates: { lat: 23.2599, lng: 77.3910 }, googlePlaceId: "ChIJJ8k_JBtofDkROt6xEGgkdnY", rating: 4.3, ratingCount: 1034, open24x7: true, status: "green" },
  { hospitalName: "BMHRC", fullName: "Bhopal Memorial Hospital and Research Centre", type: "Government – Research", category: "Super Speciality", area: "Bhanpur", address: "Bhopal Bypass Rd, BMHRC Campus, Bhanpur, Bhopal, MP 462038", emergency: true, phone: "+91-755-274-2212", totalBeds: 350, availableBeds: 120, icuBeds: 40, icuAvailable: 8, ventilators: 30, ventilatorsAvailable: 5, specialties: ["Oncology", "Nephrology", "Cardiology", "Neurology", "Respiratory Medicine", "Pulmonology"], accreditation: ["NABH"], ayushmanEmpanelled: true, coordinates: { lat: 23.2989, lng: 77.4176 }, googlePlaceId: "ChIJTUbPW1ZofDkRSLkc8QFjcI0", rating: 3.9, ratingCount: 442, open24x7: true, status: "green" },
  { hospitalName: "Bansal Hospital", fullName: "Bansal Hospital Bhopal", type: "Private", category: "Multi-Speciality", area: "Shahpura", address: "Chuna Bhatti Rd, Manisha Market, Sector C, Shahpura, Bhopal, MP 462039", emergency: true, phone: "+91-755-408-6000", totalBeds: 400, availableBeds: 180, icuBeds: 50, icuAvailable: 12, ventilators: 30, ventilatorsAvailable: 8, specialties: ["Cardiology", "Neurology", "Orthopedics", "Urology", "Gastroenterology", "Oncology", "Laparoscopic Surgery", "Nephrology"], accreditation: ["NABH"], ayushmanEmpanelled: true, coordinates: { lat: 23.1995, lng: 77.4199 }, googlePlaceId: "ChIJjdeUmbxDfDkRgkow8TwzAXo", rating: 4.0, ratingCount: 3000, open24x7: true, status: "green" },
  { hospitalName: "Chirayu Hospital", fullName: "Chirayu Medical College & Hospital", type: "Private – Teaching", category: "Multi-Speciality", area: "Bairagarh", address: "Bhopal Byp, Bhainsakhedi, Bairagarh, Bhopal, MP 462030", emergency: true, phone: "+91-755-270-9101", totalBeds: 750, availableBeds: 300, icuBeds: 80, icuAvailable: 20, ventilators: 50, ventilatorsAvailable: 12, specialties: ["General Medicine", "Surgery", "Cardiology", "Pediatrics", "Gynecology", "Orthopedics", "Radiology", "Neurology"], accreditation: ["NABH", "MCI"], ayushmanEmpanelled: true, coordinates: { lat: 23.2690, lng: 77.3081 }, googlePlaceId: "ChIJffbp_mxnfDkRk92T6rsidWs", rating: 3.3, ratingCount: 660, open24x7: true, status: "green" },
  { hospitalName: "Apollo Sage Hospital", fullName: "ApolloSage Hospitals Bhopal", type: "Private", category: "Multi-Speciality", area: "Bawadiya Kalan", address: "Bawadiya Kalan, Salaiya, Bhopal, MP 462026", emergency: true, phone: "+91-93039-72510", totalBeds: 350, availableBeds: 150, icuBeds: 60, icuAvailable: 15, ventilators: 40, ventilatorsAvailable: 10, specialties: ["Cardiology", "Organ Transplant", "Neurology", "Radiology", "Oncology", "Orthopedics", "Maternity", "Laparoscopy"], accreditation: ["NABH"], ayushmanEmpanelled: false, coordinates: { lat: 23.1776, lng: 77.4424 }, googlePlaceId: "ChIJq6pqJpFDfDkRKKXAC8PIw6w", rating: 4.5, ratingCount: 3500, open24x7: true, status: "green" },
  { hospitalName: "People's Hospital", fullName: "People's Hospital Bhopal", type: "Private – Teaching", category: "Multi-Speciality", area: "Bhanpur", address: "Ayodhya Bypass Rd, Peoples Campus, Bhanpur, Bhopal, MP 462037", emergency: true, phone: "+91-755-400-5000", totalBeds: 700, availableBeds: 280, icuBeds: 80, icuAvailable: 18, ventilators: 50, ventilatorsAvailable: 12, specialties: ["Neonatology", "Pediatrics", "Cardiology", "Orthopedics", "Neurology", "Gastroenterology", "Gynecology", "Oncology"], accreditation: ["NABH"], ayushmanEmpanelled: true, coordinates: { lat: 23.3011, lng: 77.4246 }, googlePlaceId: "ChIJ6y5SaHhpfDkRhNepztICD5E", rating: 4.5, ratingCount: 961, open24x7: true, status: "green" },
  { hospitalName: "JP Hospital", fullName: "Jai Prakash District Hospital", type: "Government", category: "District Hospital", area: "Shivaji Nagar", address: "Shivaji Nagar, Bhopal, MP 462003", emergency: true, phone: "+91-755-266-0248", totalBeds: 300, availableBeds: 80, icuBeds: 30, icuAvailable: 5, ventilators: 20, ventilatorsAvailable: 4, specialties: ["General Medicine", "Surgery", "Obstetrics", "Gynecology", "Pediatrics", "Emergency Care"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.2301, lng: 77.4178 }, googlePlaceId: "ChIJPZXThxJDfDkRKC5HCN6cj8M", rating: 3.6, ratingCount: 424, open24x7: true, status: "amber" },
  { hospitalName: "Narmada Trauma Centre", fullName: "Narmada Trauma Centre Pvt Ltd", type: "Private", category: "Multi-Speciality & Trauma", area: "Arera Colony", address: "E3/23, Arera Colony, Bhopal, MP 462016", emergency: true, phone: "+91-755-404-0000", totalBeds: 200, availableBeds: 60, icuBeds: 30, icuAvailable: 10, ventilators: 20, ventilatorsAvailable: 8, specialties: ["Trauma Surgery", "Orthopedics", "Neurosurgery", "Emergency Medicine", "General Surgery", "Critical Care"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.2177, lng: 77.4392 }, googlePlaceId: "ChIJZYkIA09CfDkRGy7f3_GIe3g", rating: 4.1, ratingCount: 515, open24x7: true, status: "green" },
  { hospitalName: "Lake City Hospital", fullName: "Lake City Hospital", type: "Private", category: "Multi-Speciality", area: "Kasturba Nagar", address: "B-27, Near Chetak Bridge, Sector B, Kasturba Nagar, Bhopal, MP 462011", emergency: true, phone: "+91-755-428-8656", totalBeds: 150, availableBeds: 40, icuBeds: 20, icuAvailable: 4, ventilators: 12, ventilatorsAvailable: 2, specialties: ["General Surgery", "Gynecology", "Laparoscopy", "Burns", "Plastic Surgery", "Cleft Lip", "Dermatology", "Pediatrics"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.2324, lng: 77.4399 }, googlePlaceId: "ChIJtSlT3mlCfDkRhFqoeRR_FZk", rating: 3.7, ratingCount: 199, open24x7: true, status: "green" },
  { hospitalName: "JK Hospital", fullName: "JK Hospital Medical Research Center", type: "Private", category: "Multi-Speciality", area: "Kolar Road", address: "Sarvadharam C Sector, Shirdipuram, Kolar Rd, Bhopal, MP 462042", emergency: true, phone: "+91-755-408-7000", totalBeds: 300, availableBeds: 90, icuBeds: 30, icuAvailable: 12, ventilators: 20, ventilatorsAvailable: 6, specialties: ["Orthopedics", "ENT", "Ophthalmology", "Gynecology", "Pediatrics", "Radiology", "General Surgery"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.1790, lng: 77.4279 }, googlePlaceId: "ChIJ-___vglDfDkR27uOWLo6cwo", rating: 3.3, ratingCount: 594, open24x7: true, status: "green" },
  { hospitalName: "Sultania Zanana Hospital", fullName: "Sultaniya Zanana Hospital (Women & Children)", type: "Government", category: "Speciality – Women & Children", area: "Jahangirabad", address: "Sultania Rd, Near Kali Mandir, Quasipura, Jahangirabad, Bhopal, MP 462001", emergency: true, phone: "+91-755-273-0124", totalBeds: 400, availableBeds: 100, icuBeds: 30, icuAvailable: 0, ventilators: 15, ventilatorsAvailable: 0, specialties: ["Obstetrics", "Gynecology", "Pediatrics", "Neonatal Care", "High-Risk Pregnancy"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.2561, lng: 77.4093 }, googlePlaceId: "ChIJy6GCyCJofDkROo6xjXjPtQE", rating: 3.4, ratingCount: 109, open24x7: true, status: "amber" },
  { hospitalName: "Kamla Nehru Hospital", fullName: "Kamla Nehru Hospital (Cancer)", type: "Government – Teaching", category: "Speciality – Cancer", area: "Royal Market", address: "VIP Road, Opp Hamidia Hospital, Royal Market, Peer Gate, Bhopal, MP 462001", emergency: false, phone: "+91-755-273-9101", totalBeds: 200, availableBeds: 50, icuBeds: 15, icuAvailable: 2, ventilators: 10, ventilatorsAvailable: 1, specialties: ["Oncology", "Cancer Surgery", "Radiotherapy", "Gastroenterology"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.2586, lng: 77.3925 }, googlePlaceId: "ChIJRdNCcRtofDkRAbwgUuD57_s", rating: 3.6, ratingCount: 66, open24x7: true, status: "amber" },
  { hospitalName: "JN Cancer Hospital", fullName: "Jawaharlal Nehru Cancer Hospital and Research Centre", type: "Government", category: "Speciality – Cancer", area: "Idgah Hills", address: "P.B. No.32, Cancer Hospital Rd, Idgah Hills, Bhopal, MP 462001", emergency: false, phone: "+91-755-266-5720", totalBeds: 250, availableBeds: 80, icuBeds: 20, icuAvailable: 5, ventilators: 15, ventilatorsAvailable: 3, specialties: ["Oncology", "Radiotherapy", "Chemotherapy", "Surgical Oncology", "Cancer Research"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.2730, lng: 77.3806 }, googlePlaceId: "ChIJp3oiykFofDkR2BkHS8nQ4R0", rating: 3.9, ratingCount: 508, open24x7: false, status: "green" },
  { hospitalName: "Navodaya Cancer Hospital", fullName: "Navodaya Cancer Hospital and Research Centre", type: "Private", category: "Speciality – Cancer", area: "Indrapuri", address: "Nizamuddin Rd, Opp BHEL Gate #1, Indrapuri B Sector, Bhopal, MP 462022", emergency: false, phone: "+91-83054-66883", totalBeds: 100, availableBeds: 30, icuBeds: 10, icuAvailable: 2, ventilators: 8, ventilatorsAvailable: 1, specialties: ["Medical Oncology", "Surgical Oncology", "Chemotherapy", "Radiotherapy"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.2530, lng: 77.4617 }, googlePlaceId: "ChIJGQPRigZCfDkRRAi3PGxjvjM", rating: 3.3, ratingCount: 133, open24x7: false, status: "green" },
  { hospitalName: "Sharda Hospital", fullName: "Sharda Hospital", type: "Private", category: "Multi-Speciality", area: "Aradhana Nagar", address: "189, Geetanjali Rd, Aradhana Nagar, Bhopal, MP 462003", emergency: true, phone: "+91-755-277-4378", totalBeds: 100, availableBeds: 45, icuBeds: 15, icuAvailable: 6, ventilators: 10, ventilatorsAvailable: 2, specialties: ["General Surgery", "Laparoscopy", "Gastroenterology", "Dermatology", "Anorectal Surgery"], accreditation: [], ayushmanEmpanelled: false, coordinates: { lat: 23.2215, lng: 77.3960 }, googlePlaceId: "ChIJJead9MNCfDkRCMgHOx6Y0pg", rating: 4.3, ratingCount: 239, open24x7: true, status: "green" },
  { hospitalName: "Noble Hospital", fullName: "Noble Multispeciality Hospital", type: "Private", category: "Multi-Speciality", area: "Misrod", address: "269/1, Near Capital Mall, Misrod, Bhopal, MP 462026", emergency: true, phone: "+91-755-248-8008", totalBeds: 110, availableBeds: 35, icuBeds: 20, icuAvailable: 4, ventilators: 12, ventilatorsAvailable: 2, specialties: ["Cardiology", "Orthopedics", "Neurology", "Dialysis", "Emergency Medicine", "General Surgery"], accreditation: ["NABH"], ayushmanEmpanelled: true, coordinates: { lat: 23.1614, lng: 77.4710 }, googlePlaceId: "ChIJh5vxYqpGfDkRE9pHFE3EG0c", rating: 4.4, ratingCount: 1261, open24x7: true, status: "green" },
  { hospitalName: "Krishna Cancer Hospital", fullName: "Krishna Cancer Hospital", type: "Private", category: "Speciality – Cancer", area: "Bawadiya Kalan", address: "Sahyog Vihar, near Shahpura, Nav Door Sanchar Nagar, Bawadiya Kalan, Bhopal, MP 462039", emergency: false, phone: "+91-755-491-9919", totalBeds: 80, availableBeds: 20, icuBeds: 10, icuAvailable: 3, ventilators: 6, ventilatorsAvailable: 2, specialties: ["Medical Oncology", "Surgical Oncology", "Chemotherapy", "Cancer Screening"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.1867, lng: 77.4355 }, googlePlaceId: "ChIJAQAAwKZDfDkRsgU2gLMDt_A", rating: 4.7, ratingCount: 491, open24x7: false, status: "green" },
  { hospitalName: "Siddhanta Hospital", fullName: "Siddhanta Red Cross Superspeciality Hospital", type: "Private", category: "Super Speciality", area: "Shivaji Nagar", address: "Link Rd 1, Shivaji Nagar, Bhopal, MP 462011", emergency: true, phone: "+91-755-257-2555", totalBeds: 120, availableBeds: 40, icuBeds: 20, icuAvailable: 10, ventilators: 15, ventilatorsAvailable: 5, specialties: ["Cardiology", "Cardiac Surgery", "Neurology", "Nephrology", "Critical Care", "Emergency Medicine"], accreditation: ["NABH"], ayushmanEmpanelled: true, coordinates: { lat: 23.2308, lng: 77.4200 }, googlePlaceId: "ChIJF-_EDlpDfDkR-yORhH9_Sw4", rating: 4.5, ratingCount: 231, open24x7: true, status: "green" },
  { hospitalName: "ASG Eye Hospital", fullName: "ASG Eye Hospital Bhopal", type: "Private", category: "Speciality – Eye", area: "Shivaji Nagar", address: "Mahadev Commercial Complex, Near Board Office, Shivaji Nagar, Bhopal, MP 462011", emergency: false, phone: "+91-674-617-2350", totalBeds: 50, availableBeds: 25, icuBeds: 0, icuAvailable: 0, ventilators: 0, ventilatorsAvailable: 0, specialties: ["LASIK Surgery", "Cataract Surgery", "Glaucoma", "ICL Procedure", "Cornea", "Retina", "Pediatric Ophthalmology"], accreditation: [], ayushmanEmpanelled: false, coordinates: { lat: 23.2305, lng: 77.4310 }, googlePlaceId: "ChIJl-axWzlDfDkRC9lKdXdR8dQ", rating: 4.9, ratingCount: 14452, open24x7: false, status: "green" },
  { hospitalName: "Carewell Hospital", fullName: "Carewell Multispeciality Hospital", type: "Private", category: "Multi-Speciality", area: "Lalghati", address: "Gufa Mandir Rd, Vitthal Nagar, Nayapura, Lalghati, Bhopal, MP 462001", emergency: true, phone: "+91-70007-47155", totalBeds: 150, availableBeds: 50, icuBeds: 20, icuAvailable: 4, ventilators: 15, ventilatorsAvailable: 3, specialties: ["Laparoscopy", "Cardiac Surgery", "Laser Surgery", "Anorectal Surgery", "General Medicine", "Emergency Care"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.2815, lng: 77.3769 }, googlePlaceId: "ChIJh7Er7TppfDkROehsjPzyT0w", rating: 4.4, ratingCount: 62, open24x7: true, status: "green" },
  { hospitalName: "RK Hospital", fullName: "R.K. Hospital and Research Centre", type: "Private", category: "Multi-Speciality", area: "Indrapuri", address: "226-C, Raisen Rd, Sector C, Indrapuri, Bhopal, MP 462022", emergency: true, phone: "+91-755-426-0605", totalBeds: 100, availableBeds: 40, icuBeds: 15, icuAvailable: 3, ventilators: 10, ventilatorsAvailable: 2, specialties: ["Laparoscopy", "Hernia Surgery", "General Surgery", "Orthopedics", "Gastroenterology"], accreditation: [], ayushmanEmpanelled: true, coordinates: { lat: 23.2523, lng: 77.4664 }, googlePlaceId: "ChIJT8XTZQFCfDkRM1ygBYOaPYU", rating: 3.4, ratingCount: 67, open24x7: true, status: "green" },
  { hospitalName: "Sai Hospital", fullName: "Sai Hospital & Trauma Center", type: "Private", category: "Multi-Speciality & Trauma", area: "Raisen Road", address: "21/1, Anandnagar, Raisen Rd, Bhopal, MP 462022", emergency: true, phone: "+91-755-405-9003", totalBeds: 80, availableBeds: 25, icuBeds: 10, icuAvailable: 2, ventilators: 8, ventilatorsAvailable: 1, specialties: ["Trauma Surgery", "Emergency Medicine", "General Surgery", "Orthopedics"], accreditation: [], ayushmanEmpanelled: false, coordinates: { lat: 23.2500, lng: 77.4881 }, googlePlaceId: "ChIJ8bgWh79DfDkRIxnduUqbjO8", rating: 3.7, ratingCount: 31, open24x7: true, status: "amber" },
  { hospitalName: "Citi Hospital", fullName: "Citi Multispeciality Hospital", type: "Private", category: "Multi-Speciality", area: "Govindpura", address: "MIG 215-216, Gautam Nagar, Housing Board Colony, Govindpura, Bhopal, MP 462011", emergency: true, phone: "+91-755-427-2669", totalBeds: 80, availableBeds: 30, icuBeds: 12, icuAvailable: 4, ventilators: 8, ventilatorsAvailable: 2, specialties: ["Cardiology", "General Medicine", "Surgery", "Emergency Care"], accreditation: [], ayushmanEmpanelled: false, coordinates: { lat: 23.2351, lng: 77.4411 }, googlePlaceId: "ChIJ____L2lCfDkRDdJqNmGx_Oc", rating: 3.9, ratingCount: 100, open24x7: true, status: "green" }
];

async function seedDB() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ MongoDB Connected');

    // Clear existing data
    await Hospital.deleteMany({});
    console.log('🗑️  Old data cleared');

    // Insert all hospitals
    const inserted = await Hospital.insertMany(hospitals);
    console.log(`🏥 ${inserted.length} hospitals inserted successfully!`);

    // Show summary
    const count = await Hospital.countDocuments();
    console.log(`📊 Total hospitals in DB: ${count}`);

    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
}

seedDB();
